apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-eiffel-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adapter
  template:
    metadata:
      labels:
        app: adapter
    spec:
      containers:
        - name: adapter
          image: localhost/gitlab-eiffel-adapter:dev
          ports:
            - containerPort: 8080
          env:
            - name: RABBIT_URL
              value: "amqp://guest:guest@192.168.49.2:31672/"

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-eiffel-adapter
spec:
  selector:
    app: adapter
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
